[package]
name = "sddm2rpm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bzip2 = "0.4.3"
clap = "2.33.3"
flate2 = "1.0.20"
handlebars = "4.1.2"
rpm-rs = { git = "https://github.com/advaithm/rpm-rs.git" }
serde = { version="1.0.129",  features = ["serde_derive"] }
tar = "0.4.37"
walkdir = "2.3.2"
xz2 = "0.1.6"
